import type { IProject } from '@/lib/models/Project';

const IMG = '/images';

export const seedProjects: IProject[] = [
  {
    id: 'phase-1',
    title: 'PVS Coco Farmland Phase-1',
    category: 'Farmland',
    location: 'Pathakotta, Hosur',
    status: 'Ongoing',
    price: 'From ₹8.5 Lakhs',
    image: `${IMG}/gallery-img3.jpg`,
    gallery: [
      `${IMG}/gallery-img3.jpg`,
      `${IMG}/img18.jpg`,
      `${IMG}/img19.jpg`,
      `${IMG}/gallery-img6.jpg`,
      `${IMG}/gallery-img7.jpg`,
      `${IMG}/gallery-img2.jpg`,
      `${IMG}/gallery-img11.jpg`,
      `${IMG}/gallery-img12.jpg`,
    ],
    description:
      'Premium coco farmland plots with clear titles, gated community access, and sustainable farming infrastructure near Hosur.',
    features: ['Clear Title', 'Gated Community', 'Coco Plantation', 'Water Source'],
    amenities: ['Security', 'Internal Roads', 'Electricity', 'Fencing'],
    benefits: ['High ROI potential', 'Weekend getaway', 'Organic farming'],
    progress: 75,
    goal: { label: 'Plots Sold', value: '85%' },
    youtubeId: 'MFFPP6BPYik',
    videos: ['MFFPP6BPYik'],
    timeline: { start: '2022', completion: '2025' },
    details: { area: '1200 sq.ft+', units: '150+ plots', rera: 'Available on request' },
    featured: true,
    seo: {
      title: 'PVS Coco Farmland Phase-1 | Hosur',
      description: 'Own premium coco farmland plots at Pathakotta, Hosur with PVS Promoters.',
    },
  },
  {
    id: 'phase-2',
    title: 'PVS Coco Farmland Phase-2',
    category: 'Farmland',
    location: 'Pathakotta-2, Hosur',
    status: 'Ongoing',
    price: 'From ₹9 Lakhs',
    image: `${IMG}/gallery-img13.jpg`,
    gallery: [
      `${IMG}/gallery-img13.jpg`,
      `${IMG}/img20.jpg`,
      `${IMG}/img21.jpg`,
      `${IMG}/gallery-img10.jpg`,
      `${IMG}/gallery-img11.jpg`,
      `${IMG}/gallery-img12.jpg`,
      `${IMG}/gallery-img14.jpg`,
      `${IMG}/gallery-img15.jpg`,
      `${IMG}/gallery-img16.jpg`,
      `${IMG}/gallery-img17.jpg`,
      `${IMG}/gallery-img18.jpg`,
      `${IMG}/img76.jpg`,
      `${IMG}/img77.jpg`,
      `${IMG}/img78.jpg`,
    ],
    description:
      'Phase 2 expansion with upgraded amenities, wider roads, and enhanced plantation support for investors and nature lovers.',
    features: ['DTCP Approved Layout', 'Plantation Support', 'Clubhouse Access'],
    amenities: ['Swimming Pool', 'Children Park', 'Street Lights'],
    benefits: ['Appreciation corridor', 'Managed farmland', 'Rental income potential'],
    progress: 60,
    goal: { label: 'Development', value: '60%' },
    youtubeId: 'I8oYfqJXVz4',
    videos: ['I8oYfqJXVz4', 'MFFPP6BPYik', 'UiBCDHTRM2U', 'WszjDmn56oo'],
    featured: true,
    seo: {
      title: 'PVS Coco Farmland Phase-2 | Hosur',
      description: 'Phase 2 coco farmland at Pathakotta with modern amenities and clear documentation.',
    },
  },
  {
    id: 'shoolagiri',
    title: 'Coco Farmland Shoolagiri',
    category: 'Farmland',
    location: 'Shoolagiri, Tamil Nadu',
    status: 'Available',
    price: 'Enquire Now',
    image: `${IMG}/img24.jpg`,
    gallery: [
      `${IMG}/img24.jpg`,
      `${IMG}/gallery-img1.jpg`,
      `${IMG}/gallery-img2.jpg`,
      `${IMG}/gallery-img11.jpg`,
      `${IMG}/gallery-img8.jpg`,
      `${IMG}/img18.jpg`,
      `${IMG}/img19.jpg`,
    ],
    description:
      'Scenic farmland project near Shoolagiri with highway connectivity and lush green surroundings ideal for weekend homes.',
    features: ['Highway Access', 'Green Surroundings', 'Flexible Plot Sizes'],
    amenities: ['Security Cabin', 'Borewell', 'Plantation'],
    benefits: ['Peaceful living', 'Investment growth', 'Eco-friendly lifestyle'],
    progress: 40,
    videos: ['UiBCDHTRM2U'],
    featured: true,
    seo: {
      title: 'Coco Farmland Shoolagiri | PVS Promoters',
      description: 'Farmland plots near Shoolagiri with excellent connectivity and natural beauty.',
    },
  },
  {
    id: 'emerald-estate',
    title: 'The Emerald Estate',
    category: 'Residential',
    location: 'Hosur, Tamil Nadu',
    status: 'Ongoing',
    price: '₹1.2 Cr+',
    image: `${IMG}/gallery-img4.jpg`,
    gallery: [
      `${IMG}/gallery-img4.jpg`,
      `${IMG}/gallery-img5.jpg`,
      `${IMG}/gallery-img8.jpg`,
      `${IMG}/gallery-img9.jpg`,
      `${IMG}/gallery-img10.jpg`,
    ],
    description:
      'Luxury villa plots with premium amenities, landscaped surroundings, and world-class lifestyle offerings.',
    features: ['Luxury Villas', 'Premium Amenities', 'Gated Community'],
    amenities: ['Clubhouse', 'Landscaped Gardens', '24/7 Security'],
    benefits: ['Premium lifestyle', 'Strong appreciation', 'Exclusive community'],
    progress: 55,
    featured: true,
    details: { area: '2400 - 4500 sq.ft', units: 'Limited plots', rera: 'On request' },
    seo: {
      title: 'Emerald Estate | Luxury Plots Hosur',
      description: 'Premium residential plots at Emerald Estate by PVS Promoters.',
    },
  },
  {
    id: 'shanvi-garden-city',
    title: 'Shanvi Garden City',
    category: 'Residential',
    location: 'Kamandotti to Uddanapalli Road',
    status: 'Available',
    price: '₹1,799/sqft',
    image: `${IMG}/gallery-img5.jpg`,
    gallery: [`${IMG}/gallery-img5.jpg`, `${IMG}/gallery-img9.jpg`, `${IMG}/gallery-img4.jpg`, `${IMG}/gallery-img7.jpg`],
    description: 'Premium gated community plots with excellent connectivity and future investment value.',
    features: ['Premium Plots', 'Gated Community', 'Best Future Investment'],
    amenities: ['Internal Roads', 'Drainage', 'Street Lights'],
    benefits: ['High growth corridor', 'Family-friendly layout', 'Clear documentation'],
    featured: true,
    seo: { title: 'Shanvi Garden City', description: 'Premium plots on Kamandotti to Uddanapalli Road.' },
  },
  {
    id: 'shanvi-garden-city-ii',
    title: 'Shanvi Garden City II',
    category: 'Residential',
    location: 'Bangalore-Krishnagiri Highway',
    status: 'Ongoing',
    price: 'In Progress',
    image: `${IMG}/gallery-img7.jpg`,
    gallery: [`${IMG}/gallery-img7.jpg`, `${IMG}/gallery-img12.jpg`, `${IMG}/gallery-img6.jpg`, `${IMG}/gallery-img10.jpg`],
    description: 'Phase II residential layout with highway access and active site development.',
    features: ['Highway Access', 'Development in Progress', 'Residential Layout'],
    benefits: ['Strategic location', 'Active development', 'Investment potential'],
    progress: 45,
    featured: false,
    seo: { title: 'Shanvi Garden City II', description: 'Ongoing residential layout on Bangalore-Krishnagiri Highway.' },
  },
  {
    id: 'village-farm-house',
    title: 'Village Farm House',
    category: 'Farmland',
    location: 'Thally Road, Hosur',
    status: 'Available',
    price: 'Premium',
    image: `${IMG}/gallery-img2.jpg`,
    gallery: [`${IMG}/gallery-img2.jpg`, `${IMG}/gallery-img6.jpg`, `${IMG}/gallery-img8.jpg`, `${IMG}/gallery-img1.jpg`],
    description: 'New launch farm house plots with minimum buildup options and gated security.',
    features: ['New Launch', '5000 sqft Plots', '1000 sqft Min Buildup'],
    amenities: ['Gated Entry', 'Community Pool', 'Landscaping'],
    benefits: ['Weekend retreat', 'Managed community', 'Flexible build options'],
    featured: false,
    seo: { title: 'Village Farm House Hosur', description: 'Farm house plots on Thally Road, Hosur.' },
  },
  {
    id: 'village-farm-phase-1',
    title: 'Village Farm Phase I',
    category: 'Farmland',
    location: 'Hosur, Tamil Nadu',
    status: 'Available',
    price: 'Luxury',
    image: `${IMG}/gallery-img1.jpg`,
    gallery: [`${IMG}/gallery-img1.jpg`, `${IMG}/gallery-img11.jpg`, `${IMG}/gallery-img3.jpg`, `${IMG}/gallery-img9.jpg`],
    description: 'Gated and secured farm community with swimming pool and premium lifestyle features.',
    features: ['Swimming Pool', 'Gated & Secured', 'Limited Availability'],
    amenities: ['Security', 'Pool', 'Clubhouse'],
    benefits: ['Luxury farm living', 'Secure investment', 'Resort-style amenities'],
    featured: false,
    seo: { title: 'Village Farm Phase I', description: 'Luxury farm community in Hosur.' },
  },
];
